### ISSUE TITLE
[ANSWERED] A 1.1.4 realease for minecraft 1.8?

### ISSUE THREAD

**Issue by beppe9000** [chylex/Better-Sprinting#14]
I am stuck with 1.8 because the  macro/keybind mod is 1.8-only.

**Comment by chylex** [comment]
Sorry, no backports. Only the latest available version of Minecraft is supported with very rare exceptions, and 1.8 is not going to be one.

**Comment by beppe9000** [comment]
Are these the only missing things that will actually matter?
- Added key unbinding by pressing Escape
- Fixed visual bug with sneaking not player height
- Fixed visual bug with wrong head rotation in third person camera
- Fixed a bug where disabling the mod on server with toggle sprint/sneak on would lock the state, until the player re-joined the server

**Comment by chylex** [comment]
I assume you're using 1.8 and not 1.8.9, in which case you're missing all features from version 1.1.2 onwards.

**Comment by beppe9000** [comment]
Is there any other than those I listed above?

**Comment by chylex** [comment]
Possibly, you can view all changelogs when you click 'Files' on http://bsprint.chylex.com

**Comment by beppe9000** [comment]
Thanks :\
