### ISSUE TITLE
[DONE] Localization update

### ISSUE THREAD

**Issue by chylex** [chylex/Better-Sprinting#15]
Added two new strings: https://github.com/chylex/Better-Sprinting/commit/874e2190a94f7c776ff809559b5583fad326de0e#diff-b66e92c61286d5a94ba4e78b44b35738L15

Pinging everyone who PR'd localization:
@Adaptivity 
@Vexatos 
@Mazdallier 
@3TUSK 
@NatsuArashi 

EDIT: I added localization of bs.autoJump, so only bs.autoJump.info is needed.

**Comment by 3TUSK** [comment]
Which branch? Or you will cheery-pick them?
Anyhow, #17

**Comment by chylex** [comment]
Sorry I didn't give you enough time, I'm going to release another version in a couple days with all localization finished and some minor tweaks.

**Comment by chylex** [comment]
@litosns this is a ping
