### ISSUE TITLE
[FIXED 1.1.3] Crash on startup.

### ISSUE THREAD

**Issue by Claycorp** [chylex/Better-Sprinting#2]
http://pastebin.com/YtEiV3Kt

**Comment by chylex** [comment]
Install PlayerAPI. If that doesn't work, there is an incompatible mod if it happens right on startup. If it happens when you switch worlds or MP, let me know.

**Comment by Claycorp** [comment]
Seems to be fine now.
Thanks!
(Sorry i did not notice the message on CF saying to add PlayerAPI if things did not work on its own.)

**Comment by chylex** [comment]
I'll keep it open and see what could have caused it.

**Comment by chylex** [comment]
Added some protection, so hopefully the issue doesn't happen under the unknown circumstances.
