### ISSUE TITLE
[INVALID] Space in filename

### ISSUE THREAD

**Issue by C0rn3j** [chylex/Better-Sprinting#26]
Hi, this mod is one of the few that have a space in the filename, would you consider replacing it with an underscore? Thanks!

http://i.imgur.com/A4KSJQI.png

It breaks my program, which I'm planning to fix, but I think it'd be better if mods had consistent naming too ^^

**Comment by chylex** [comment]
Should probably just fix the bug, this is the same format I use for 3 other mods, one vastly more popular than better sprinting :P

**Comment by C0rn3j** [comment]
Fair enough!
