### ISSUE TITLE
Flyspeed from Draconic Evolution don't work. (1.7.x)

### ISSUE THREAD

**Issue by ghost** [chylex/Better-Sprinting#29]
The Flyspeed from Draconic Evolution's Draconic Armor don't work with Bettersprinting.
Maybe make a Option that allows to disable the whole flying script. But otherwise it is for me one of the best Minecraft mods. <3

**Comment by chylex** [comment]
1.7 is not supported, and besides, Better Sprinting replaces the entire movement system so I'm afraid there is no easy way to fix this.
