### ISSUE TITLE
Crash when clicking Controls

### ISSUE THREAD

**Issue by a-frenzy** [chylex/Better-Sprinting#31]
https://gist.github.com/frenzye/b2e53d537ccafd46f2897d81342359b4

**Comment by chylex** [comment]
@jaredlll08 Any idea on how to make this compatible w/ Controlling? https://github.com/chylex/Better-Sprinting/blob/master/src/main/java/chylex/bettersprinting/client/ClientEventHandler.java#L69-L73

**Comment by jaredlll08** [comment]
If I understand this correctly, you are removing keybinds form the list right?

**Comment by chylex** [comment]
Yea, removing keybinds and also replacing a button (but that part should be fine).

**Comment by XvSkItZvX** [comment]
I Arrived at this page after experiencing the same crash on clicking the "Controls" button under "Options". 
Controlling mod is in the pack as well. The sole purpose of the mod collection I am using is Client UI. I will save the crash and post upon request, as to not clutter this thread, and will gladly compile a list of mods used in the current collection. 

[EDIT] This is happening in Minecraft 1.12 - Better Sprinting "Release 2.0.1 for MC 1.12" - Controlling "Controlling-3.0.1"

**Comment by chylex** [comment]
Crash will be fixed on Controlling's side, minor visual issues arising from the fact it's suddenly working will be fixed in the next Better Sprinting update.

**Comment by XvSkItZvX** [comment]
Awesome good to know! thanks for the response.
