### ISSUE TITLE
InputUpdateEvent is not triggered

### ISSUE THREAD

**Issue by boq** [chylex/Better-Sprinting#32]
Since 1.12.2-14.23.0.2527 (https://github.com/MinecraftForge/MinecraftForge/pull/4356) Forge adds `InputUpdateEvent` which is triggered from `EntityPlayerSP.onLivingUpdate`. It seems your patch does not re-implement that functionality.

This breaks OpenBlocks' elevators.

**Comment by chylex** [comment]
BSM for 1.12.2 was released before 2527. I can look into it soon, but after migrating my CurseForge to Twitch I can't login anymore, so I'll have to figure that out first.

**Comment by chylex** [comment]
Update released.
