### ISSUE TITLE
Fix sprint glitch

### ISSUE THREAD

**Issue by SuperOP535** [chylex/Better-Sprinting#34]
togglesprint
Sometimes when you start sprinting and hit a block it will give the classic sprint glitch which starts & stops sprint forever until you stop it..

**Comment by chylex** [comment]
Yea, idk if that's ever gonna be fixed, not really planning to figure that bug out right now.

**Comment by SuperOP535** [comment]
ok i guess i will look for another mod

**Comment by chylex** [comment]
Can't reproduce the issue, apparently vanilla fixed this in 1.9...

**Comment by SuperOP535** [comment]
Funny thing is that I was playing 1.12.2 back then

**Comment by chylex** [comment]
I need an exact scenario in which I can reliably reproduce the bug, otherwise I can't fix it.

**Comment by SuperOP535** [comment]
I don't remember, nor do I use mods or play Minecraft anymore. I'm sorry
