### ISSUE TITLE
Incompatible with controlling

### ISSUE THREAD

**Issue by theshadowake** [chylex/Better-Sprinting#36]
Controls - Better sprintings button doesn't show when using the controlling mod.

**Comment by chylex** [comment]
Can you access the menu in-game by pressing 'O'?

**Comment by theshadowake** [comment]
Yep, just the button that doesn't show, but the hotkey isn't as intuitive as the button for modpack users.

**Comment by chylex** [comment]
Well, BSM always attempts to add the button even if another mod like Controlling uses its own GUI for the Controls, so if that didn't work for whatever reason, idk if there's much I can do.

**Comment by theshadowake** [comment]
OK thanks for letting me know. I've passed this over to Jared (the controlling dev):
https://github.com/jaredlll08/Controlling/issues/27
