### ISSUE TITLE
[Request] 1.2.5 Source

### ISSUE THREAD

**Issue by pablo67340** [chylex/Better-Sprinting#39]
Hey there,

I have been browsing the internet for the source of this mod from 1.2.5 Minecraft and cannot seem to find it. Reason being is there appears to be coremods, which effect the class "vq". We have another coremod already developed in this class which means installing BetterSprinting would overwrite our class edits. I am looking for the source so I can manually merge our changes with BetterSprinting's so we can have both mods co-exist in one class.

If you need to get in contact with me:
Email: pablo67340@gmail.com
Discord: Bryce#0001

**Comment by chylex** [comment]
The only change I can find in `vq`/`EntityPlayerSP` is

```java
if (onGround && flag2 && !isUsingItem() && !isPotionActive(Potion.blindness))
{
    setSprinting(((MovementInputFromOptions)movementInput).sprint);/* CHANGED STUFF
    if (sprintToggleTimer == 0)
    {
        sprintToggleTimer = 7;
    }
    else
    {
        setSprinting(true);
        sprintToggleTimer = 0;
    }*/
}
```
where `MovementInputFromOptions.sprint` is also added by the mod.

**Comment by pablo67340** [comment]
Thank you so much for getting back to me, I did not think you'd be able to help me considering how old of a version I'm working with! Is there any possibility you'd be able to share the rest of the source? Im unable to compile my mods with your changes in them due to missing imports/vars, so I'd think it would be best if I combine your source into my mod, and deal with the mixing like so.

**Comment by chylex** [comment]
You can add a `public boolean sprint;` into `MovementInputFromOptions` to fix the compile error, and then replace it with the original class file from the mod (that is, unless your mod is also modifying this particular class; if so, I'll figure out how to get the full source up but that'll take a few days).

**Comment by pablo67340** [comment]
Ill try this out, I havent had much time to mess around with this because of work. Supposed to be a weekend chore, anyways, when I try this out ill post my result here, however i am sure it would be a much bigger help if you could find the source. Take your time on it, I understand people are busy so I am in no rush. Thank you so much for helping me with this!

**Comment by chylex** [comment]
https://github.com/chylex/Better-Sprinting/tree/legacy

**Comment by pablo67340** [comment]
Thank you so much for sharing the legacy source, not only for 1.2.5 but for every version beyond. 10/10 Github'manship.
