### ISSUE TITLE
Relicensing to MPL 2.0

### ISSUE THREAD

**Issue by chylex** [chylex/Better-Sprinting#40]
Right now, Better Sprinting has no open-source license, only a set of exceptions for modpacks. I'm intending to change the license to the open-source [MPL 2.0](https://www.mozilla.org/en-US/MPL/2.0/FAQ/). The new license will apply to:

- All source code in this repository, with the exception of the `legacy` branch
- All asset files (primarily translation files) in this repository
- **Retroactively**, to all binaries published on [CurseForge](https://minecraft.curseforge.com/projects/better-sprinting/files), as the new license doesn't add any restrictions over the previous license; this will not apply if one or more contributors don't give consent

If you are mentioned in the list below, please provide consent in a comment. You can use the sample:

> I, `username`, agree to relicense my contributions to Better Sprinting under the MPL 2.0 license.

Feel free to also comment with any questions or objections to the new license.

If one or more contributors don't provide consent, their contributions will be removed and I will release updated binaries with the new license.

## Contributors

| Consent | Account | Notes |
|:----------|:---------|:-------|
|<ul><li>- [x] </li></ul>| @Vexatos | `de_DE.lang` |
|<ul><li>- [x] </li></ul>| @davrodrila | `es_ES.lang` |
|<ul><li>- [ ] </li></ul>| @Mazdallier | `fr_FR.lang` |
|<ul><li>- [x] </li></ul>| @Haruki1 | `lt_LT.lang` |
|<ul><li>- [x] </li></ul>| @AndreiTS | `pt_BR.lang` |
|<ul><li>- [ ] </li></ul>| @Adaptivity | `ru_RU.lang` |
|<ul><li>- [x] </li></ul>| @MCEventHorizon | `sr_SP.lang` |
|<ul><li>- [x] </li></ul>| @3TUSK | `zh_CN.lang` |
|<ul><li>- [x] </li></ul>| @NatsuArashi | `zh_TW.lang` |
|<ul><li>- [x] </li></ul>| @KovuTheHusky | #25 |

**Comment by Vexatos** [comment]
I, Vexatos, agree to relicense my contributions to Better Sprinting under the MPL 2.0 license.

**Comment by davrodrila** [comment]
I, davrodrila, agree to relicense my contributions to Better Sprinting under the MPL 2.0 license

**Comment by 3TUSK** [comment]
> What? Another relicensing effort?!

I, 3TUSK, agree to relicense my contributions to Better Sprinting under the MPL 2.0 license.

**Comment by KovuTheHusky** [comment]
I, KovuTheHusky, agree to relicense my contributions to Better Sprinting under the MPL 2.0 license.

**Comment by AndreiTS** [comment]
I, AndreiTS, agree to relicense my contributions to Better Sprinting under the MPL 2.0 license.

**Comment by NatsuArashi** [comment]
I,  NatsuArashi, agree to relicense my contributions to Better Sprinting under the MPL 2.0 license.

**Comment by MCEventHorizon** [comment]
I, MCEventHorizon, agree to relicense my contributions to Better Sprinting
under the MPL 2.0 license.

**Comment by theLucy** [comment]
I, Haruki1, agree to relicense my contributions to Better Sprinting under the MPL 2.0 license.

**Comment by chylex** [comment]
Unfortunately I don't know how to get in touch with @Mazdallier and @Adaptivity, so the plan right now is to begin a 1.14 port excluding their commits, and sometime soon go back through popular older versions, and backport features and fixes. All builds from this point on will be under MPL 2.0.

If @Mazdallier and @Adaptivity respond with consent, I will re-add their commits into the new builds.

**Comment by labpaw** [comment]
If you still need it, feel free to do anything with my changes (it's just lang file)
Anyway, I, Adaptivity, agree to relicense my contributions to Better Sprinting under the MPL 2.0 license.
