### ISSUE TITLE
Indicator

### ISSUE THREAD

**Issue by Aericio** [chylex/Better-Sprinting#41]
Could there be an indicator text somewhere that shows that the sprint is toggled or not? It's just useful so that I can see it's on without having to test by moving (or when I sometimes just don't know if its on at all).

If you can, I'm requesting this to be put into 1.8.9 too.

**Comment by chylex** [comment]
Not considering an indicator right now, but you can hit the Sprint (hold) key once without moving to reset the toggle.

**Comment by Aericio** [comment]
Ah, I see. Thank you.
