### ISSUE TITLE
[1.14.2] Client crash when clicking options controls

### ISSUE THREAD

**Issue by ProsperCraft** [chylex/Better-Sprinting#44]
https://gist.github.com/ProsperCraft/0f08cf488aa978a729ae0dfeed869db4

It looks like this may be a two year old issue - https://github.com/chylex/Better-Sprinting/issues/31

**Comment by ProsperCraft** [comment]
Removing Controlling stopped the crash.

https://minecraft.curseforge.com/projects/controlling?comment=40

**Comment by chylex** [comment]
Try with Controlling 5.0.2.

**Comment by chylex** [comment]
Also fixed on Better Sprinting's side, but there are a few potential issues I need to look into before I release an update.
