### ISSUE TITLE
[1.14.4] On keybinds and config files and modpacks.

### ISSUE THREAD

**Issue by ProsperCraft** [chylex/Better-Sprinting#52]
I use default settings mod to distribute my keybinds to players that do not already have an options.txt however because your keybinds are not stored there, every time a player updates the pack their better sprinting keybinds are wiped back to my settings.

The benefit to default settings mod is that if they have an options.txt it doesn't get overwritten on pack updates so they don't have to remap their keybinds every time I update.

Is it possible to save to the options.txt so we don't have players complaining?

**Comment by chylex** [comment]
Keybinds *are* saved in options.txt, and they *should* take priority on all but the first run.

If the Better Sprinting config file doesn't exist, that counts as the first run and the keybinds are reset based on current sprint/sneak keys, there are no de facto defaults. Does updating the pack cause the mod to think it's running for the very first time?

**Comment by ProsperCraft** [comment]
There is a crash on first run lately, related to a config, I have not isolated what that is from.

I don't think your mod thinks it is first run, it gets my settings.

**Comment by ProsperCraft** [comment]
[bettersprinting-client.zip](https://github.com/chylex/Better-Sprinting/files/3454475/bettersprinting-client.zip)

**Comment by chylex** [comment]
Using `1.14.4-forge-28.0.11`, if I change a keybind in `bettersprinting-client.toml` and run the game, the change gets ignored because it's already registered in `options.txt`. The only reason I can think of, why the keybinds should get reset, is if the client config is deleted, but that would lose *all* settings anyway so it's a bigger issue.

**Comment by ProsperCraft** [comment]
The Twitch launcher wipes all mods and configs when it installs updates.

Might want to test with 1.14.4 - 28.0.27

**Comment by chylex** [comment]
How is that a problem in the mod then... deleting config files means you lose your config. If the keybinds were kept, you'd still lose everything else.

**Comment by chylex** [comment]
Closing the issue. Twitch deleting configs obviously causes the configs to be lost, it's not indvidual mods' job to hack around that.
