### ISSUE TITLE
[1.14.4] strange conflict with BiomesOPlenty

### ISSUE THREAD

**Issue by sarifynna** [chylex/Better-Sprinting#53]
Hi!

A strange conflict exists between your mod and biomes o' plenty. With just better sprinting and biomes o' plenty enabled I found that the ability to select biomes o' plenty as the world type is no longer possible.

I hope this can be resolved soon, thanks!

Here are the versions tested in as well as the log:
forge-28.0.45
BetterSprinting-1.14.4-v3.0.1
BiomesOPlenty-1.14.4-9.0.0.222-universal
[latest.log](https://github.com/chylex/Better-Sprinting/files/3488839/latest.log)

**Comment by chylex** [comment]
Better Sprinting does not properly run on Forge 28.0.45, and neither will many other mods due to breaking API changes. I'll look into an update soon, until then I'd recommend downgrading to 28.0.41 and making sure you don't use mods that have been updated to 28.0.45 until all of them are.

**Comment by sarifynna** [comment]
ok, thanks!
