### ISSUE TITLE
Better Sprinting Controls don't show up

### ISSUE THREAD

**Issue by RadioCougar** [chylex/Better-Sprinting#54]
So I have betterssprinting for 1.14.4-v3.0.1 and I have forge and optifine both for 1.14.4 but when I go into the game no button for the better sprinting controls shows up at the top of the controls panel, but It knows that bettersprinting is there because in the controls panel there is a small section titles better sprinting with one keybind named sprint that controls my sprint keybind. However this is very frustrating because I cannot get a togglesprint or togglesneak keybind. also pressing o in game does not bring up the bettersprinting control panel.

**Comment by chylex** [comment]
Always try removing optifine first before reporting issues in mods, it often doesn't play nice.

EDIT: You didn't say which version of Forge you have, if you're using 28.0.45 or newer, you need to update Better Sprinting to 3.0.1a.

**Comment by RadioCougar** [comment]
thanks issue solved I needed the 3.0.1a

**Comment by RadioCougar** [comment]
wait lmao now this new version doesn't work with the current optifine that I have for 1.14.4, it crashes when I press controls, is there any optifine version for 1.14.4 that is compatible with forge and bettersprinting?

**Comment by chylex** [comment]
Use older Forge that works with Better Sprinting 3.0.1, it's mentioned in the changelog on curseforge.
