### ISSUE TITLE
Toggle Sprint on screen

### ISSUE THREAD

**Issue by Nanasae123** [chylex/Better-Sprinting#60]
Hi so I was wondering if there is a way to get some indication on my screen that toggle sprint is on? Sometimes its hard to tell without moving.

**Comment by chylex** [comment]
You can make sure the toggle is off by tapping the sprint key once, even when you're not moving. I will not be adding new features to Better Sprinting and instead focus on [Better Controls](https://github.com/chylex/Better-Controls), which also has a keybind to reset all toggles at once.
