### ISSUE TITLE
[1.8.9] Crash with mousedelayfix 1.0.1

### ISSUE THREAD

**Issue by Chromosome83** [chylex/Better-Sprinting#62]
WARNING: coremods are present:
  FMLLoadingPlugin (MouseDelayFix-1.0.1.jar)
  BetterSprintingCore (BetterSprinting-1.8.9-v2.3.0.jar)
Contact their authors BEFORE contacting forge

**Comment by chylex** [comment]
I don't support 1.8 anymore.
